############################################################################################
################################### application ############################################
############################################################################################
application:
  name: 配置中心消息总线动态刷新版客户端1-v1.2